routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Controller@index')->name('welcome');
Route::feeds();
Auth::routes();

Route::prefix('blog')->group(function () {
   Route::get('/', 'BlogController@index');
});
Route::prefix('dashboard')->group(function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('/stats', 'DashboardController@stats')->name('dashboard.stats');
    Route::get('/breakdown', 'DashboardController@breakdown')->name('dashboard.breakdown');
    Route::get('/history', 'DashboardController@history')->name('dashboard.history');
    Route::get('/detail/{symbol}', 'DashboardController@coinDetail')->name('dashboard.coin-detail');

    Route::get('/holdings/by-coin', 'DashboardController@byCoin')->name('holdings.by-coin');
    Route::get('/holdings/by-purchase', 'DashboardController@byPurchase')->name('holdings.by-purchase');

    Route::post('/add/usd-to-coin', 'TransactionsController@store')->name('transactions.store');
    Route::get('/transactions/all', 'DashboardController@getAllTransactions');
    Route::get('/transactions/delete/{id}', 'TransactionsController@destroy')->name('transactions.destroy');

    Route::post('/trade/btc-to-coin', 'TradesController@btcToCoin');
    Route::post('/trade/coin-to-btc', 'TradesController@coinToBtc');
    Route::post('/trade/eth-to-coin', 'TradesController@ethToCoin');
    Route::post('/trade/coin-to-eth', 'TradesController@coinToEth');
    Route::get('/get-trades', 'TradesController@getTrades');
    Route::get('/trades/delete/{id}', 'TradesController@destroy')->name('trades.destroy');

    Route::post('/sell-coins', 'SalesController@store');
    Route::get('/sales/all', 'SalesController@getSales');
    Route::get('/sales/delete/{id}', 'SalesController@destroy')->name('sales.destroy');

    Route::get('/sort', 'UsersSortController@getSort');
    Route::post('/sort', 'UsersSortController@store');

    Route::get('/watchlist', 'WatchlistController@getWatchlist');
    Route::post('/watchlist', 'WatchlistController@store')->name('watchlist.store');
    Route::get('/watchlist/delete/{id}', 'WatchlistController@destroy')->name('watchlist.destroy');
    Route::get('/watchlist/available-coins', 'WatchlistController@availableCoins');

    Route::get('/dark-mode', 'DashboardController@darkMode')->name('dark-mode');

    Route::get('/is-admin', 'DashboardController@isAdmin');

    Route::post('/hide-low-holdings', 'DashboardController@hideLowHoldings');

});

Route::prefix('/settings')->group(function() {
    Route::get('/', 'SettingsController@index')->name('settings');
    Route::get('/api', 'SettingsController@api')->name('settings.api');
    Route::view('/subscription', 'subscription');
    Route::post('/subscription/create', 'SubscriptionsController@store');
});

Route::prefix('admin')->middleware(\App\Http\Middleware\IsWriter::class)->group(function() {
    Route::view('/', 'admin.admin')->name('admin.dashboard');
    Route::post('/add-post', 'BlogController@store');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


Route::get('/coins/get', 'CoinsController@get');
Route::get('/coins/get/symbols', 'CoinsController@getSymbols');
Route::resource('coins', 'CoinsController');
Route::view('/help', 'help')->name('help');
Route::get('/ticker', 'Controller@getTicker');
Route::get('/test', 'TestController@index')->name('test');
Route::get('/cryptocompare/{coin}/{priceIn}', 'ExternalApiController@cryptoCompare');

Route::get('/updateCoins', 'CoinsController@updatePrices');
Route::get('/importCoins', 'CoinsController@importCoins');
Route::view('/changelog', 'changelog');

Route::post('/guru-bot', 'SlackController@guruQuote');

Route::get('/api/all', 'UsersApiController@getApis');
Route::get('/api/gdax', 'UsersApiController@getGdax');
Route::post('/api/gdax', 'UsersApiController@storeGdax')->name('api.gdax.store');
Route::get('/api/gdax/delete/{id}', 'UsersApiController@destroyGdax')->name('api.gdax.destroy');
Route::get('/api/binance', 'UsersApiController@getBinance');
Route::post('/api/binance', 'UsersApiController@storeBinance')->name('api.binance.store');
Route::get('/api/binance/delete/{id}', 'UsersApiController@destroyBinance')->name('api.binance.destroy');
Route::get('/api/bittrex', 'UsersApiController@getBittrex');
Route::post('/api/bittrex', 'UsersApiController@storeBittrex');
Route::get('/api/bittrex/delete/{id}', 'UsersApiController@destroyBittrex');
Route::get('/api/coinbase/delete{id}', 'UsersApiController@destroyCoinbase')->name('api.coinbase.destroy');



Route::get('/coinbase/oauth', 'CoinbaseImportController@redirectToCoinbase')->name('coinbase.oauth');
Route::get('/coinbase/refresh', 'CoinbaseImportController@refreshToken')->name('coinbase.oauth.refresh');
Route::get('/coinbase/callback', 'CoinbaseImportController@handleCoinbaseCallback');
Route::get('/coinbase/query', 'CoinbaseImportController@queryCoinbase')->name('coinbase.requery');
Route::get('/coinbase/retrieve-import', 'CoinbaseImportController@retrieveImport');
Route::post('/coinbase/import', 'CoinbaseImportController@handleImport');
Route::view('/coinbase/test', 'dashboard.import-coins.coinbase-import');
Route::get('/coinbase/already-imported', 'CoinbaseImportController@retrieveImported');
Route::post('/coinbase/delete-previous', 'CoinbaseImportController@deletePrevious');
Route::get('/coinbase/missing-transactions', 'CoinbaseImportController@retrieveMissingTransactions');

Route::get('/gdax/fetch', 'GdaxImportController@getFromApi');
Route::get('/gdax/table', 'GdaxImportController@table');
Route::view('/gdax/show-import', 'dashboard.import-coins.gdax-import');
Route::post('/gdax/handle-import', 'GdaxImportController@handleImport');
Route::post('/gdax/mark-as-imported', 'GdaxImportController@markAsImported');
Route::get('/gdax/already-imported', 'GdaxImportController@retrieveImported');
Route::post('/gdax/delete-previous', 'GdaxImportController@deletePrevious');
Route::get('/gdax/missing-transactions', 'GdaxImportController@retrieveMissingTransactions');


Route::view('/binance', 'dashboard.import-coins.binance-import')->name('binance');
Route::post('/binance/import', 'BinanceImportController@importFromExcel');
Route::get('/binance/fetch', 'BinanceImportController@getFromApi');
Route::get('/binance/retrieve-import', 'BinanceImportController@retrieveImport');
Route::post('/binance/handle-import', 'BinanceImportController@handleImport');
Route::get('/binance/missing-trades', 'BinanceImportController@retrieveMissingTrades');

Route::get('/fixmissinggdax', 'GdaxImportController@retrieveMissingIds');

Route::get('/sitemap.xml', 'Controller@sitemap');

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/cryptocoins.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        @include('layouts.nav')

        <div class="container">
            <div class="row">
                <div class="columns">
                    <div class="column is-2">
                        <aside class="menu">
                            <p class="menu-label">
                                General
                            </p>
                            <ul class="menu-list">
                                <li><a class="{{ Nav::isRoute('dashboard') }}" href="{{ route('dashboard') }}">Home</a></li>
                                <li><a class="{{ Nav::hasSegment('my-coins', 2) }}" href="{{ route('my-coins') }}">My Coins</a></li>
                            </ul>
                        </aside>
                    </div>
                    <div class="column is-10">
                        @yield('content')
                    </div>
                </div>
            </div>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    {{--<script type="text/javascript">--}}
    {{--@stack('javascript')--}}
        {{--$( document ).ready(function() {--}}
            {{--@stack('jquery')--}}
        {{--});--}}
    {{--</script>--}}
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer">
    <div class="container">
        <div class="columns is-vcentered">
            <div class="column has-text-centered">
                <img src="{{ asset('img/thecoinguru.png') }}" style="height:120px">
            </div>
            <div class="column has-text-centered">
                <p>
                    <strong>My Coin Guru</strong> by <a href="https://coryrose.com" target="_blank" rel="noopener">Cory Rosenwald</a>
                    <br>
                    Currency data provided by <a href="https://coinmarketcap.com" target="_blank" rel="noopener">CoinMarketCap.com</a>
                </p>
            </div>
            <div class="column has-text-centered">
                <donate-eth-modal></donate-eth-modal>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/nav.blade.php
<nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
    <div class="container">
    <div class="navbar-brand">
        <a class="navbar-item has-text-weight-bold" href="/">
            <img src="{{ asset('img/guru.svg') }}" style="width:26px;height:36px;max-height:none;">&nbsp;My Coin Guru
        </a>
        <a class="navbar-item is-hidden-desktop" href="https://join.slack.com/t/mycoinguru/shared_invite/enQtMjkzNTQ1NjI1MjE4LWMxNGFhZGRhOWZjMWM0YzJhYzg5OWRlZTZjYTcxNmM4MmMzNjYwYWYwM2I3NmEyOGZmZjU1ZGExMTc3NjY5ODk">
                <span class="icon">
                    <i class="fa fa-slack"></i>
                </span>
        </a>

        <button class="button navbar-burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
        </button>
    </div>
    <div class="navbar-menu" id="navMenu">
        <div class="navbar-start">
                <a href="{{ route('dashboard') }}" class="navbar-item is-tab {{ Nav::hasSegment('dashboard', 1) }}">Dashboard</a>
            <a href="{{ route('coins.index') }}" class="navbar-item is-tab {{ Nav::hasSegment('coins', 1) }}">Coins</a>
            <a href="/changelog" class="navbar-item is-tab {{ Nav::hasSegment('changelog', 1) }}">Changelog</a>
        </div>
        <div class="navbar-end">
            <a class="navbar-item is-hidden-touch" href="https://join.slack.com/t/mycoinguru/shared_invite/enQtMjkzNTQ1NjI1MjE4LWMxNGFhZGRhOWZjMWM0YzJhYzg5OWRlZTZjYTcxNmM4MmMzNjYwYWYwM2I3NmEyOGZmZjU1ZGExMTc3NjY5ODk">
                <span class="icon" style="vertical-align: middle">
                                    <i class="fa fa-slack"></i>
                                </span>
            </a>
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">Help</a>
                <div class="navbar-dropdown">
                    <a href="/help" class="navbar-item">Help Guide</a>
                    <a href="mailto:coryrosenwald@gmail.com?subject=My Coin Guru Question/Feedback" class="navbar-item">Questions/Feedback</a>
                </div>
            </div>
            @guest
                <a href="{{ route('login') }}" class="navbar-item">Login</a>
                <a href="{{ route('register') }}" class="navbar-item">Sign Up</a>
                @else
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            @if (Auth::user()->subscribed('Monthly') || Auth::user()->subscribed('Yearly'))
                                <i class="fa fa-certificate" aria-hidden="true" style="color:goldenrod"></i>&nbsp;{{ Auth::user()->name }}
                                @else
                                {{ Auth::user()->name }}
                                @endif

                        </a>

                        <div class="navbar-dropdown">
                            <a class="navbar-item" href="{{ route('settings') }}">Account Settings</a>
                            @writer
                            <a class="navbar-item" href="{{ route('admin.dashboard') }}">Admin Dashboard</a>
                            @endwriter
                            @if (Auth::user()->dark_mode == 0)
                            <a class="navbar-item" href="{{ route('dark-mode') }}">Dark Mode</a>
                            @else
                                <a class="navbar-item" href="{{ route('dark-mode') }}">Light Mode</a>
                                @endif
                            <a class="navbar-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form>
                        </div>
                    </div>
                @endif
        </div>
    </div>
    </div>
</nav>

@push('javascript')
    document.addEventListener('DOMContentLoaded', function () {

    // Get all "navbar-burger" elements
    var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach(function ($el) {
    $el.addEventListener('click', function () {

    // Get the target from the "data-target" attribute
    var target = $el.dataset.target;
    var $target = document.getElementById(target);

    // Toggle the class on both the "navbar-burger" and the "navbar-menu"
    $el.classList.toggle('is-active');
    $target.classList.toggle('is-active');

    });
    });
    }

    });
    @endpush